jobs:
  - name: update-keystore-data-integration
    max_in_flight: 1
    plan:
      - get: dataworks-analytical-frontend-service
        trigger: true
        passed:
          - update-keystore-data-qa
      - .: (( inject meta.plan.terraform-dataworks-analytical-frontend-service-bootstrap ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
      - .: (( inject meta.plan.terraform-output-frontend-service ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.put-keystore-data ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager"

  - name: update-keystore-data-external-integration
    max_in_flight: 1
    plan:
      - get: dataworks-analytical-frontend-service
        trigger: true
        passed:
          - update-keystore-data-external-qa
      - .: (( inject meta.plan.terraform-dataworks-analytical-frontend-service-bootstrap ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
      - .: (( inject meta.plan.terraform-output-frontend-service ))
        config:
          params:
            TF_WORKSPACE: integration
      - .: (( inject meta.plan.put-keystore-data ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager/azkaban_external"
