jobs:
  - name: update-keystore-data-preprod
    max_in_flight: 1
    plan:
      - get: dataworks-analytical-frontend-service
        trigger: true
        passed:
          - update-keystore-data-integration
      - .: (( inject meta.plan.terraform-dataworks-analytical-frontend-service-bootstrap ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
      - .: (( inject meta.plan.terraform-output-frontend-service ))
        config:
          params:
            TF_WORKSPACE: preprod
      - .: (( inject meta.plan.put-keystore-data ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager"

  - name: update-keystore-data-external-preprod
    max_in_flight: 1
    plan:
      - get: dataworks-analytical-frontend-service
        trigger: true
        passed:
          - update-keystore-data-external-integration
      - .: (( inject meta.plan.terraform-dataworks-analytical-frontend-service-bootstrap ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
      - .: (( inject meta.plan.terraform-output-frontend-service ))
        config:
          params:
            TF_WORKSPACE: preprod
      - .: (( inject meta.plan.put-keystore-data ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager/azkaban_external"
