jobs:
  - name: perform-python-format-dev
    max_in_flight: 1
    plan:
      - get: aws-azkaban
      - get: aws-azkaban-dev
        trigger: true
      # - .: ((inject meta.plan.set-up-python-3-7))
      #   input_mapping:
      #     aws-azkaban: aws-azkaban-dev
      - .: ((inject meta.plan.install-tox-new))
      - .: ((inject meta.plan.tox-unit-tests))
        input_mapping:
          aws-azkaban: aws-azkaban-dev
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management-dev)):role/ci
