jobs:
  - name: e2e
    max_in_flight: 1
    plan:
      - get: aws-azkaban
        resource: aws-azkaban-e2e
      - .: (( inject meta.plan.terraform-bootstrap-azkaban ))
      - .: (( inject meta.plan.terraform-output-azkaban ))
      - .: (( inject meta.plan.running-jobs ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
#      - .: (( inject meta.plan.cycle-azkaban-containers ))
#        config:
#          params:
#            AWS_ACC: ((aws_account.development))
#            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
#            EXECUTOR_NAME: "azkaban-external-executor"
#            WEBSERVER_NAME: "azkaban-external-webserver"
#            LAMBDA_NAME: "truncate_external_table_lambda"
      - .: (( inject meta.plan.await-azkaban-webserver ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            WEBSERVER_SERVICE: "azkaban-external-webserver"
      - .: (( inject meta.plan.create-e2e-project-files ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
      - .: (( inject meta.plan.create-e2e-project ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
      - .: (( inject meta.plan.execute-e2e-flow ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
      - .: (( inject meta.plan.monitor-e2e-flow ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
