jobs:
  - name: integration
    max_in_flight: 1
    plan:
      - get: aws-azkaban
        trigger: true
        passed:
          - qa
      - get: manage-mysql-user-release
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'integration'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'integration'

  - name: rotate-mysql-password-master-integration
    plan:
      - get: secrets-management
        trigger: false
      - .: (( inject meta.plan.rotate-mysql-master-password ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            DB_NAME: "azkaban-database"
            SECRET_ID: "azkaban-master-rds-password"
          inputs:
            - name: secrets-management

  - name: rotate-mysql-password-external-master-integration
    plan:
      - get: secrets-management
        trigger: false
      - .: (( inject meta.plan.rotate-mysql-master-password ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            DB_NAME: "azkaban-external-database"
            SECRET_ID: "azkaban-external-master-rds-password"
          inputs:
            - name: secrets-management

  - name: rotate-azkaban-webserver-password-integration
    plan:
      - .: (( inject meta.plan.rotate-azkaban-webserver-password ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: rotate-azkaban-executor-password-integration
    plan:
      - .: (( inject meta.plan.rotate-azkaban-executor-password ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci

  - name: cycle-azkaban-containers-integration
    plan:
      - get: aws-azkaban
        trigger: false
      - get: manage-mysql-user-release
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-output ))
        params:
          TF_WORKSPACE: 'integration'
      - .: (( inject meta.plan.cycle-azkaban-containers ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
        ensure:
          .: (( inject meta.plan.terraform-apply ))
          params:
            TF_WORKSPACE: 'integration'

  - name: rotate-azkaban-admin-password-integration
    plan:
      - .: (( inject meta.plan.rotate-azkaban-admin-password ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager"

  - name: rotate-azkaban-external-admin-password-integration
    plan:
      - .: (( inject meta.plan.rotate-azkaban-admin-password ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager/azkaban_external"
