jobs:
  - name: aws-azkaban-pr
    plan:
      - get: aws-azkaban-pr
        trigger: true
        version: every
      - get: impact-measures
      - put: aws-azkaban-pr
        params:
          path: aws-azkaban-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          aws-azkaban: aws-azkaban-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          aws-azkaban: aws-azkaban-pr
        params:
          DETAILED_EXITCODE: ''
        on_failure:
          put: aws-azkaban-pr
          params:
            path: aws-azkaban-pr
            status: failure
        on_success:
          put: aws-azkaban-pr
          params:
            path: aws-azkaban-pr
            status: success
