jobs:
  - name: preprod
    max_in_flight: 1
    plan:
      - get: aws-azkaban
        trigger: true
        passed:
          - integration
      - get: manage-mysql-user-release
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'preprod'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'preprod'

  - name: rotate-mysql-password-master-preprod
    plan:
      - get: secrets-management
        trigger: false
      - .: (( inject meta.plan.rotate-mysql-master-password ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
          inputs:
            - name: secrets-management

  - name: rotate-azkaban-webserver-password-preprod
    plan:
      - .: (( inject meta.plan.rotate-azkaban-webserver-password ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci

  - name: rotate-azkaban-executor-password-preprod
    plan:
      - .: (( inject meta.plan.rotate-azkaban-executor-password ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci

  - name: cycle-azkaban-executor-preprod
    plan:
      - get: aws-azkaban
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-output ))
        params:
          TF_WORKSPACE: 'preprod'
      - .: (( inject meta.plan.cycle-azkaban-executor ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'preprod'
