jobs:
  - name: production
    max_in_flight: 1
    plan:
      - get: aws-azkaban
        trigger: true
        passed:
          - preprod
      - get: manage-mysql-user-release
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'production'

  - name: rotate-mysql-password-master-production
    plan:
      - get: secrets-management
        trigger: false
      - .: (( inject meta.plan.rotate-mysql-master-password ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
          inputs:
            - name: secrets-management

  - name: rotate-azkaban-webserver-password-production
    plan:
      - .: (( inject meta.plan.rotate-azkaban-webserver-password ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci

  - name: rotate-azkaban-executor-password-production
    plan:
      - .: (( inject meta.plan.rotate-azkaban-executor-password ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci

  - name: cycle-azkaban-containers-production
    plan:
      - get: aws-azkaban
        trigger: false
      - get: manage-mysql-user-release
        trigger: false
      - get: midnight-trigger
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-output ))
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta.plan.cycle-azkaban-containers ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'production'
