jobs:
  - name: qa
    max_in_flight: 1
    plan:
      - get: aws-azkaban
        trigger: true
        passed:
          - development
      - get: manage-mysql-user-release
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'qa'
  - name: rotate-mysql-password-master-qa
    plan:
      - get: secrets-management
        trigger: false
      - .: (( inject meta.plan.rotate-mysql-master-password ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
          inputs:
            - name: secrets-management

  - name: rotate-azkaban-webserver-password-qa
    plan:
      - .: (( inject meta.plan.rotate-azkaban-webserver-password ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: rotate-azkaban-executor-password-qa
    plan:
      - .: (( inject meta.plan.rotate-azkaban-executor-password ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci

  - name: cycle-azkaban-containers-qa
    plan:
      - get: aws-azkaban
        trigger: false
      - get: manage-mysql-user-release
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-output ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.cycle-azkaban-containers ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
        ensure:
          .: (( inject meta.plan.terraform-apply ))
          params:
            TF_WORKSPACE: 'qa'

  - name: rotate-azkaban-admin-password-qa
    plan:
      - .: (( inject meta.plan.rotate-azkaban-admin-password ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager"

  - name: rotate-azkaban-external-admin-password-qa
    plan:
      - .: (( inject meta.plan.rotate-azkaban-admin-password ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager/azkaban_external"
