jobs:
  - name: azkaban-admin-cognito-mgmt-dev
    plan:
      - get: dataworks-cognito
      - .: (( inject meta.plan.terraform-bootstrap-dataworks-cognito ))
        params:
          TF_WORKSPACE: management-dev
          AWS_SECRETS_ROLE: arn:aws:iam::((aws_account.management-dev)):role/ci
      - .: (( inject meta.plan.generate-random-password ))
        params:
          AWS_ACC: ((aws_account.management-dev))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management-dev)):role/ci
      - .: (( inject meta.plan.terraform-output-dataworks-cognito ))
      - .: (( inject meta.plan.update-cognito-user-password ))
        params:
          AWS_ACC: ((aws_account.management-dev))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management-dev)):role/ci
      - in_parallel:
        - .: (( inject meta.plan.update-secretsmanager-secret-password ))
          params:
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager/azkaban_external/cognito"
        - .: (( inject meta.plan.update-secretsmanager-secret-password ))
          params:
            AWS_ACC: ((aws_account.qa))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager/azkaban_external/cognito"
        - .: (( inject meta.plan.update-secretsmanager-secret-password ))
          params:
            AWS_ACC: ((aws_account.integration))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
            SECRET_ID: "/concourse/dataworks/workflow_manager/azkaban_external/cognito"


  - name: azkaban-admin-cognito-management
    plan:
      - get: dataworks-cognito
      - .: (( inject meta.plan.terraform-bootstrap-dataworks-cognito ))
        params:
          TF_WORKSPACE: management-dev
          AWS_SECRETS_ROLE: arn:aws:iam::((aws_account.management)):role/ci
      - .: (( inject meta.plan.generate-random-password ))
        params:
          AWS_ACC: ((aws_account.management))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
      - .: (( inject meta.plan.terraform-output-dataworks-cognito ))
      - .: (( inject meta.plan.update-cognito-user-password ))
        params:
          AWS_ACC: ((aws_account.management))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
      - in_parallel:
          - .: (( inject meta.plan.update-secretsmanager-secret-password ))
            params:
              AWS_ACC: ((aws_account.preprod))
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
              SECRET_ID: "/concourse/dataworks/workflow_manager/azkaban_external/cognito"
          - .: (( inject meta.plan.update-secretsmanager-secret-password ))
            params:
              AWS_ACC: ((aws_account.production))
              AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
              SECRET_ID: "/concourse/dataworks/workflow_manager/azkaban_external/cognito"

